

var mongoose = require('mongoose'),
autoIncrement = require('mongoose-auto-increment-fix');

autoIncrement.initialize(global.db);
var AddressScheme = new mongoose.Schema({

    contract_id: {type: String},
    contractdate:{type: Date},
    projectname: {type: String},
    codemeli: {type: String},
    requester: {type: String},
    requestid: {type: String},
    shenasname: {type: String},
    fathername: {type: String},
    birthdate: {type: Date},
    addressid: {type: String},
    tawalodcity: {type: String},
    codeposti: {type: String},
    phone: {type: String},
    phone2: {type: String},
    status: {type: String},
    buildingmanager: {type: String},
    ostan: {type: String},
    city: {type: String},
    zone: {type: String},
    tedadvahed: {type: String},
    address: {type: String},
    asansorcount: {type: String},
    sakhtemankind: {type: String},
    asansorkind: {type: String},
    stopcount: {type: String},
    asansorzarfit: {type: String},
    asansorfloordoorkind: {type: String},
    asansorcabindoorkind: {type: String},
    gearboxengine:  {type: String},
    tablofarman:  {type: String},
    breaksystem:  {type: String},
    salenasb: {type: String},
    standardvaziat:  {type: String},
    standarddate: {type: Date},
    contractduration: {type: Date},
    contractenddate: {type: Date},
    garantyenddate: {type: Date},
    servicepersal: {type: String},
    firstservicedate: {type: Date},
    nirumoghim:  {type: String},
    edaritime:  {type: String},
    noneedaritime:  {type: String},
    holidaytime: {type: String},
    roghanpeimankar:  {type: String},
    controlbeforeservice:  {type: String},
    bimestartdate: {type: Date},
    bimeenddate: {type: Date},
    bimecost: {type: String},
    bimecompany: {type: String},
    bimenumber: {type: String},
    bimepaymethod: {type: String},
    monthlycost: {type: String},
    totalcost: {type: String},
    pishpardakhtkind:  {type: String},
    mandeavalie: {type: String},
    arzeshafzude:  {type: String},
    contractmoaref: {type: String},
    contractpursant: {type: String},
    teknesian: {type: String},
    created: {type: Date, default: Date.now},
});
AddressScheme.plugin(autoIncrement.plugin, 'contract');
module.exports = db.model('contract', AddressScheme);
